/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Book.gltf --transform
Author: katrin.kor (https://sketchfab.com/katrin.701)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viking-book-c23b8c487c3c455cb8ff970a3ec3a5c2
Title: Viking book
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Book-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.MeshSG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} rotation={[-Math.PI / 2, 0, 0]} >
        
      {/* <meshStandardMaterial
          color="#579e88"
          color="#ffffff" 
          
        /> */}
        
      </mesh>

    </group>
  )
}

useGLTF.preload('/Book-transformed.glb')
